version: '3.8'

services:
  postgres_identity:
    image: postgres:15-alpine
    container_name: carimam_postgres_identity
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pa5svword321carr1mann
      POSTGRES_DB: carimam_identity
    ports:
      - "8432:5432"
    volumes:
      - pgdata_identity:/var/lib/postgresql/data

  postgres_product:
    image: postgres:15-alpine
    container_name: carimam_postgres_product
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pa5svword321carr1mann
      POSTGRES_DB: carimam_product
    ports:
      - "8433:5432"
    volumes:
      - pgdata_product:/var/lib/postgresql/data

  postgres_order:
    image: postgres:15-alpine
    container_name: carimam_postgres_order
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pa5svword321carr1mann
      POSTGRES_DB: carimam_order
    ports:
      - "8434:5432"
    volumes:
      - pgdata_order:/var/lib/postgresql/data

volumes:
  pgdata_identity:
  pgdata_product:
  pgdata_order: